# Generated by Django 4.0.6 on 2022-08-07 17:08

import MH_App.models.patientStatus
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namePatient', models.CharField(max_length=100)),
                ('documentPatient', models.IntegerField()),
                ('phonePatient', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('birthDate', models.DateTimeField()),
                ('sex', models.CharField(max_length=30)),
                ('bloodType', models.CharField(max_length=30)),
                ('financier', models.CharField(max_length=30)),
                ('ethnicGroup', models.CharField(max_length=30)),
                ('patientType', models.CharField(max_length=30)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('entryDate', models.DateTimeField()),
                ('exitDate', models.DateTimeField()),
                ('registerDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('occupation', models.CharField(max_length=30, verbose_name='Occupation')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('isActive', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diseasesHistory', models.CharField(max_length=255)),
                ('medicationsHistory', models.CharField(max_length=255)),
                ('medicalAllergies', models.CharField(max_length=255)),
                ('familyHistory', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='MH_App.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hour', models.CharField(default=MH_App.models.patientStatus.get_default_my_hour, max_length=20)),
                ('paSystolic', models.IntegerField()),
                ('paDiastolic', models.IntegerField()),
                ('meanArterialPressure', models.IntegerField(blank=True, null=True)),
                ('heartRate', models.IntegerField()),
                ('respiratoryRate', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientStatus', to='MH_App.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medicalhistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatingSpecialty', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('reasonForConsultation', models.CharField(max_length=100)),
                ('diagnostic', models.CharField(max_length=100)),
                ('medication', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicalHistory', to='MH_App.patient')),
            ],
        ),
    ]
